config/routes.rb
Vitrine::Application.routes.draw do
  
  resources :ingressos_dashboards
  
  resources :acessos
  
  resources :notification
  
  resources :usuarios

  root :to => 'empresas#index'
  
  match 'empresas/conteudo/all' => 'Empresas#get_conteudos'

  resources :empresas do
    resources :conteudos
  end

  resources :empresas do
    resources :tipo_de_ingressos
  end
  
  get "empresas/index"

  resources :sessions


  resources :ingressos
  get "ingressos/index"
  
  match 'ingressos/conteudo/:conteudo_id' => 'Ingressos#get_ingressos_by_conteudo'
  match 'empresas/:empresa_id/conteudos/newvideo/new' => 'Conteudos#newt'
  match 'empresas/:empresa_id/conteudos/newpic/new' => 'Conteudos#newp'

end

app/models/conteudo.rb
class Conteudo < ActiveRecord::Base
  self.include_root_in_json = true
  belongs_to  :empresa, :foreign_key => "empresa_id", :class_name => "Empresa"
  belongs_to  :conteudo, :class_name => "Conteudo", :foreign_key => "parent_id"
  has_many    :ingressos, dependent: :destroy, :foreign_key => "conteudo_id", :class_name => "Ingresso"
  has_many    :counteudos, dependent: :destroy, :class_name => "Conteudo", :foreign_key => "parent_id"
  has_and_belongs_to_many :tipo_de_ingressos

  acts_as_tree :order => "id"
  
  #after_create :send_notification
  
  
  
  has_attached_file :imagem,
      :styles => {
      :thumb  => "100x100",
      :medium => "200x200",
      :large => "600x400",
      :icon => "42x42"
  },
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => ":attachment/:id/:style.:extension",
    :bucket => 'skynetimagens'

  has_attached_file :row_imagem,
      :styles => {
      :thumb  => "100x100",
      :medium => "200x200",
      :large => "600x400"
  },
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => ":attachment/:id/:style.:extension",
    :bucket => 'skynetimagens'
    
    
  def send_notification
    unless self.destaque == false || self.ativo == false
      #Apple notification
      unless self.empresa.token == nil
        APN.notify(self.empresa.token, :alert => self.titulo, :badge => 4, :sound => true, :other_information => self.subtitulo)
      end
       #Android c2dm
      unless self.empresa.c2dm_email == nil || self.empresa.c2dm_password == nil || self.empresa.c2dm_registration_id == nil
        SpeedyC2DM::API.set_account(self.empresa.c2dm_email, self.empresa.c2dm_password)
        options = {
          :registration_id => self.empresa.c2dm_registration_id,
          :message => self.titulo,
          :extra_data => self.id,
          :collapse_key => "some-collapse-key" #verificar o que é collapse-key
        }
        response = SpeedyC2DM::API.send_notification(options)
      end
    end
  end
  
  def as_json(options={})
     super(:include => :tipo_de_ingressos, :methods => [:imagem_url, :imagem_thumb_url,:imagem_medium_url,:imagem_large_url,:imagem_icon_url,:row_imagem_url, :row_imagem_thumb_url,:row_imagem_medium_url,:row_imagem_large_url])
  end
    
    def imagem_url
        if imagem_updated_at != nil
          imagem.url
        end
    end

    def imagem_thumb_url
      if imagem_updated_at != nil
        imagem.url(:thumb)
      end
    end

    def imagem_medium_url
      if imagem_updated_at != nil
        imagem.url(:medium)
      end
    end

    def imagem_large_url
      if imagem_updated_at != nil
        imagem.url(:large)
      end
    end

    def imagem_icon_url
      if imagem_updated_at != nil
        imagem.url(:icon)
      end
    end

    def row_imagem_url
        if row_imagem_updated_at != nil
          row_imagem.url
        end
    end

    def row_imagem_thumb_url
      if row_imagem_updated_at != nil
        row_imagem.url(:thumb)
      end
    end

    def row_imagem_medium_url
      if row_imagem_updated_at != nil
        row_imagem.url(:medium)
      end
    end

    def row_imagem_large_url
      if row_imagem_updated_at != nil
        row_imagem.url(:large)
      end
    end 
end

app/controllers/conteudos_controller.rb
class ConteudosController < ApplicationController
  
  before_filter :get_empresa, :get_tipos_de_ingresso, :checar_permissoes_empresa_dependente
  before_filter :checar_permissoes, :except => :get_conteudos
  
  def get_empresa
    @empresa = Empresa.find(params[:empresa_id])
  end
  def get_tipos_de_ingresso
    @tipo_de_ingressos = @empresa.tipo_de_ingressos
  end
  
  # GET /conteudos
  # GET /conteudos.json
  def index
    @conteudos = @empresa.conteudos.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conteudos }
    end
  end

  # GET /conteudos/1
  # GET /conteudos/1.json
  def show
    @conteudo = @empresa.conteudos.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: [@empresa, @conteudo] }
    end
  end

  # GET /conteudos/new
  # GET /conteudos/new.json
  def new
    @conteudo = Conteudo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: [@empresa, @conteudo] }
    end
  end

  # GET /conteudos/1/edit
  def edit
    @conteudo = Conteudo.find(params[:id])
  end

  # POST /conteudos
  # POST /conteudos.json
  def create
    @conteudo = @empresa.conteudos.new(params[:conteudo])

    respond_to do |format|
      if @conteudo.save
        format.html { redirect_to [@empresa, @conteudo], notice: 'Conteudo was successfully created.' }
        format.json { render json: [@empresa, @conteudo], status: :created, location: [@empresa, @conteudo] }
      else
        format.html { render action: "new" }
        format.json { render json: @conteudo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conteudos/1
  # PUT /conteudos/1.json
  def update
    @conteudo = @empresa.conteudos.find(params[:id])

    respond_to do |format|
      if @conteudo.update_attributes(params[:conteudo])
        format.html { redirect_to  [@empresa, @conteudo], notice: 'Conteudo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @conteudo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conteudos/1
  # DELETE /conteudos/1.json
  def destroy
    @conteudo = Conteudo.find(params[:id])
    @conteudo.destroy

    respond_to do |format|
      format.html { redirect_to [@empresa, @conteudo] }
      format.json { head :no_content }
    end
  end
  # GET /conteudos/new
  # GET /conteudos/new.json
  def newt
    @conteudo = Conteudo.new

    respond_to do |format|
      format.html  #newt.html.erb
      format.json { render json: [@empresa, @conteudo] }
    end
  end

  def newp
    @conteudo = Conteudo.new

    respond_to do |format|
      format.html  #newt.html.erb
      format.json { render json: [@empresa, @conteudo] }
    end
  end

end

app/helpers/conteudos_helper.rb
module ConteudosHelper


	 def display_conteudos(conteudos)
       content_tag(:div, :class => 'container') do
       	conteudos.collect do |conteudo|
           	if conteudo.parent_id == nil
           		concat(
            		content_tag(:div, :class => 'conteudo') do
            			concact_conteudo(conteudo)
            			concat(find_all_subconteudos(conteudo))
            		end
            	)
           	end
       	end
       end
    end
    
   def find_all_subconteudos(conteudo)
    if conteudo.children.size > 0
      content_tag(:div, :class => 'sub_conteudo') do
      	conteudo.children.collect do |subcat|
        	if subcat.children.size > 0
        		concat(
          			content_tag(:div,:class => 'conteudo') do
          				concact_conteudo(subcat)
          				concat(find_all_subconteudos(subcat))
          			end
          		)
        	else
        		concat(
          			content_tag(:div,:class => 'conteudo') do
          				concact_conteudo(subcat)
          			end
          		)
        	end
        end
      end
    end
  end

  def concact_conteudo(conteudo)
    concat(
        content_tag(:div,:class => 'box') do
        concat(
          content_tag(:label, conteudo.titulo, :class => 'label_titulo')

        )
        concat(
          content_tag(:label, conteudo.subtitulo, :class => 'label_subtitulo')
        )

<<<<<<< HEAD
        concat(
          link_to image_tag("/assets/shared/ticket2.png"), '/ingressos_dashboards/' + conteudo.id.to_s
=======
    concat(
      link_to('Ingressos', '/ingressos_dashboards/' + conteudo.id.to_s)
    )

  	concat(
  		link_to('Ver', [@empresa,conteudo], :class => 'link_show')
  	)
>>>>>>> 08dd1dcc0a4d79af88bcff6582e98c3797c51aaa

        )

        concat(
          
          link_to image_tag("/assets/shared/show2.png", :border=>0, :alt=> 'Mostrar', :title => 'Mostrar Conteudo'), [@empresa,conteudo]
        )

        concat(
          
          link_to image_tag("/assets/shared/editar.png", :border=>0, :alt=> 'Editar', :title => 'Editar'), edit_empresa_conteudo_path(@empresa,conteudo)
        )

        concat(
          
          link_to image_tag("/assets/shared/remover.png", :border=>0 , :alt => 'Remover', :title => 'Remover'),[@empresa,conteudo], confirm: 'Tem certeza?', method: :delete
        )
      	
      end
    )

    concat(
        content_tag(:div,:class => 'box-right') do
          concat(
          image_tag(conteudo.imagem(:thumb), :class => 'image_conteudo_thumb')
        )
  	
  end
  )
  end

end

app/views/conteudos/_form.html.erb
<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyAcEzpDs5fpjWQPAOSqaWsR2mhn6Svu_S0&sensor=true"></script>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "conteudos" %>

<% unless @conteudo.ancestors.empty? %>
<p>
<% @conteudo.ancestors.reverse.each do |conteudo| %>
  <%= link_to conteudo.titulo, [@empresa,conteudo] %> &gt;
<% end %>
</p>
<% end %>

<% unless @conteudo.children.empty? %>
<p>Conteudos</p>

<ul>
  <% @conteudo.children.reverse.each do |conteudo| %>
    <p><%= link_to conteudo.titulo, [@empresa,conteudo] %><p>
  <% end %>
</ul>
<% end %>

<%= form_for([@empresa, @conteudo], :html => { :multipart => true }) do |f| %>
  <% if @conteudo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conteudo.errors.count, "error") %> Erro ao salvar:</h2>

      <ul>
      <% @conteudo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :parent_id %>
  <%= f.hidden_field :empresa_id %>
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>
<div class="actions">
      <%= link_to image_tag("/assets/shared/voltar.png", :border=>0, :alt=> 'Voltar', :title => 'Voltar'), empresa_conteudos_path(@empresa) %>
     
    <%= f.submit "Salvar" %>
  </div>
  <div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>
  <div class="caixaesquerda">
  
    
    
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field" style="float:left;margin-right: 10px;">
    <%= f.check_box :ativo %>
    <%= f.label :ativo %>
  </div>
  <div class="field" style="float:left;margin-right: 10px;">
    <%= f.check_box :social %>
    <%= f.label :social %>
  </div>
  <div class="field">
    <%= f.check_box :destaque %>
    <%= f.label :destaque %>
  </div>
  <div class="field">
    <%= f.label :subtitulo %><br />
    <%= f.text_field :subtitulo %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :tipo_de_ingressos %><br />
    <%= f.select :tipo_de_ingresso_ids, @tipo_de_ingressos.collect {|x| [x.titulo, x.id]}, {}, :multiple => true %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.datetime_select :data %>
  </div>
  <div class="field">
    <%= f.label :data_incio_vendas %><br />
    <%= f.datetime_select :data_incio_vendas %>
  </div>
  <div class="field">
    <%= f.label :data_fim_vendas %><br />
    <%= f.datetime_select :data_fim_vendas %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br />
    <%= f.select :categoria, [['Galeria', 'galeria'], ['Imagem','imagem'], ['Menu','menu'], ['Lista', 'lista'], ['Mapa', 'mapa'], ['Notícia', 'noticia']] %>
  </div>
  </div>

  <div class="caixadireita">
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :imagem_principal %><br />
    <%= f.file_field :imagem %>
  </div>

  <div class="field">
    <%= f.label :imagem_banner %><br />
    <%= f.file_field :row_imagem %>
  </div>

  <%if @empresa.conteudos %>
	<div class="field">
	   <%= f.label :parent_id %><br />
	   <%= f.select :parent_id, @empresa.conteudos.map{ |c| [c.titulo, c.id] },:include_blank => true %>
	</div>
	
  <% end %>
  <div class="field">
    <label for="locationTypeCheckbox">Local</label>
    <input id="locationTypeCheckbox" type="checkbox" value="false"/>
  </div>
	<div id="containerLocation">
		<div class="field">
		    <%= f.label :endereco %><br />
		    <%= f.text_field :endereco %>
		</div>
		<input type="button" id="geocodingButton" value="Geolocalizar">
		<div id="map"> 
		   <div id="map_canvas" style="width:100%; height:400px"></div>
		</div>
	</div>
</div>
  
<% end %>

app/views/conteudos/_formp.html.erb
<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyAcEzpDs5fpjWQPAOSqaWsR2mhn6Svu_S0&sensor=true"></script>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "conteudos" %>

<% unless @conteudo.ancestors.empty? %>
<p>
<% @conteudo.ancestors.reverse.each do |conteudo| %>
  <%= link_to conteudo.titulo, [@empresa,conteudo] %> &gt;
<% end %>
</p>
<% end %>

<% unless @conteudo.children.empty? %>
<p>Conteudos</p>

<ul>
  <% @conteudo.children.reverse.each do |conteudo| %>
    <p><%= link_to conteudo.titulo, [@empresa,conteudo] %><p>
  <% end %>
</ul>
<% end %>

<%= form_for([@empresa, @conteudo], :html => { :multipart => true }) do |f| %>
  <% if @conteudo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conteudo.errors.count, "error") %> Erro ao salvar:</h2>

      <ul>
      <% @conteudo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :parent_id %>
  <%= f.hidden_field :empresa_id %>
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>
<div class="actions">
      <%= link_to image_tag("/assets/shared/voltar.png", :border=>0, :alt=> 'Voltar', :title => 'Voltar'), empresa_conteudos_path(@empresa) %>
     
    <%= f.submit "Salvar" %>
  </div>
  <div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>
  <div class="caixaesquerda">
  
    
    
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field" style="float:left;margin-right: 10px;">
    <%= f.check_box :ativo %>
    <%= f.label :ativo %>
  </div>
  <div class="field" style="float:left;margin-right: 10px;">
    <%= f.check_box :social %>
    <%= f.label :social %>
  </div>
  <div class="field">
    <%= f.check_box :destaque %>
    <%= f.label :destaque %>
  </div>
  <div class="field">
    <%= f.label :subtitulo %><br />
    <%= f.text_field :subtitulo %>
  </div>
  <div class="field">
    <%= f.label :imagem_principal %><br />
    <%= f.file_field :imagem %>
  </div>

  <div class="field">
    <%= f.label :imagem_banner %><br />
    <%= f.file_field :row_imagem %>
  </div>

  <%if @empresa.conteudos %>
  <div class="field">
     Qual evento pertence essa foto?<br />
     <%= f.select :parent_id, @empresa.conteudos.map{ |c| [c.titulo, c.id] },:include_blank => true %>
  </div>
  
  <% end %>
  <div class="field">
    <label for="locationTypeCheckbox">Local</label>
    <input id="locationTypeCheckbox" type="checkbox" value="false"/>
  </div>
  <div id="containerLocation">
    <div class="field">
        <%= f.label :endereco %><br />
        <%= f.text_field :endereco %>
    </div>
    <input type="button" id="geocodingButton" value="Geolocalizar">
    <div id="map"> 
       <div id="map_canvas" style="width:100%; height:400px"></div>
    </div>
  </div>
  </div>

  <div class="caixadireita">
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  
</div>
  
<% end %>

app/views/conteudos/_formt.html.erb
<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyAcEzpDs5fpjWQPAOSqaWsR2mhn6Svu_S0&sensor=true"></script>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "conteudos" %>

<% unless @conteudo.ancestors.empty? %>
<p>
<% @conteudo.ancestors.reverse.each do |conteudo| %>
  <%= link_to conteudo.titulo, [@empresa,conteudo] %> &gt;
<% end %>
</p>
<% end %>

<% unless @conteudo.children.empty? %>
<p>Conteudos</p>

<ul>
  <% @conteudo.children.reverse.each do |conteudo| %>
    <p><%= link_to conteudo.titulo, [@empresa,conteudo] %><p>
  <% end %>
</ul>
<% end %>

<%= form_for([@empresa, @conteudo], :html => { :multipart => true }) do |f| %>
  <% if @conteudo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conteudo.errors.count, "error") %> Erro ao salvar:</h2>

      <ul>
      <% @conteudo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :parent_id %>
  <%= f.hidden_field :empresa_id %>
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>
  <div class="actions">
      <%= link_to image_tag("/assets/shared/voltar.png", :border=>0, :alt=> 'Voltar', :title => 'Voltar'), empresa_conteudos_path(@empresa) %>
    <%= f.submit "Salvar" %>
  </div>
   <div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>
  <div class="caixaesquerda">
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field" style="float:left;margin-right: 10px;">
    <%= f.check_box :ativo %>
    <%= f.label :ativo %>
  </div>
  <div class="field" style="float:left;margin-right: 10px;">
    <%= f.check_box :social %>
    <%= f.label :social %>
  </div>
  <div class="field">
    <%= f.check_box :destaque %>
    <%= f.label :destaque %>
  </div>
  <div class="field">
    <%= f.label :subtitulo %><br />
    <%= f.text_field :subtitulo %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <%if @empresa.conteudos %>
  <div class="field">
     Qual evento pertence esse video?<br />
     <%= f.select :parent_id, @empresa.conteudos.map{ |c| [c.titulo, c.id] },:include_blank => true %>
  </div>
  
  <% end %>
   <div class="field">
    <%= f.label :imagem_principal %><br />
    <%= f.file_field :imagem %>
  </div>

  <div class="field">
    <%= f.label :imagem_banner %><br />
    <%= f.file_field :row_imagem %>
  </div>
  </div>

  <div class="caixadireita">
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
 

  
</div>
  
<% end %>

app/views/conteudos/edit.html.erb
<h1 style="text-align: center;margin-bottom: 30px;">Editar conteudo</h1>
<div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>

<%= render 'form' %>

app/views/conteudos/index.html.erb
<h1 style="text-align: center;margin-bottom: 30px;">Lista de conteudos</h1>
<div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>
<%= link_to image_tag("/assets/shared/voltar.png", :border=>0, :alt=> 'Voltar', :title => 'Voltar'), empresas_path %>
<%= link_to image_tag("/assets/shared/adicionareventos.png", :border=>0, :alt=> 'Adicionar novo evento', :title => 'Adicionar novo evento'), new_empresa_conteudo_path(@empresa) %>
<%= link_to image_tag("/assets/shared/adicionarvideos.png", :border=>0, :alt=> 'Adicionar novo video', :title => 'Adicionar novo video'),'/empresas/' + @empresa.id.to_s + '/conteudos/newvideo/new' %>
<%= link_to image_tag("/assets/shared/adicionarpictures.png", :border=>0, :alt=> 'Adicionar nova foto', :title => 'Adicionar nova foto'),'/empresas/' + @empresa.id.to_s + '/conteudos/newpic/new' %>
<div style="width:100%;height:2px;background:#777;margin-bottom:10px;margin-top:10px;"></div>
<%= display_conteudos(@conteudos) %>

<br />

app/views/conteudos/new.html.erb
<h1 style="text-align: center;margin-bottom: 30px;">Novo conteudo</h1>
<div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>


<%= render 'form' %>

app/views/conteudos/newp.html.erb
<h1 style="text-align: center;margin-bottom: 30px;">Novo conteudo</h1>
<div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>


<%= render 'formp' %>

app/views/conteudos/newt.html.erb
<h1 style="text-align: center;margin-bottom: 30px;">Novo video</h1>
<div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>


<%= render 'formt' %>

app/views/conteudos/show.html.erb
<h1 style="text-align: center;margin-bottom: 30px;">Conteúdo do Evento</h1>
<div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>
<%= link_to image_tag("/assets/shared/voltar.png", :border=>0, :alt=> 'Voltar', :title => 'Voltar'), empresa_conteudos_path(@empresa) %>
<%= link_to image_tag("/assets/shared/editar2.png", :border=>0, :alt=> 'Editar', :title => 'Editar'), edit_empresa_conteudo_path(@empresa, @conteudo) %>
<p id="notice"><%= notice %></p>
<div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>

<div class="caixaesquerda">
<% unless @conteudo.ancestors.empty? %>
<p>
<% @conteudo.ancestors.reverse.each do |conteudo| %>
  <%= link_to conteudo.titulo, [@empresa,conteudo] %> &gt;
<% end %>
</p>
<% end %>

<% unless @conteudo.children.empty? %>
<p>Conteudos</p>
<ul>
  <% @conteudo.children.reverse.each do |conteudo| %>
    <p><%= link_to conteudo.titulo, [@empresa,conteudo] %><p>
  <% end %>
</ul>
<% end %>


<p>
  <b>Titulo:</b>
  <%= @conteudo.titulo %>
</p>
<br/>
<p>
  <b>Subtitulo:</b>
  <%= @conteudo.subtitulo %>
</p>
<br/>
<p>
  <b>Categoria:</b>
  <%= @conteudo.categoria %>
</p>
<br/>
<p>
  <b>Descricao:</b>
  <%= @conteudo.descricao %>
</p>
<br/>
<p>
  <b>Endereco:</b>
  <%= @conteudo.endereco %>
</p>
<br/>
<p>
  <b>Latitude:</b>
  <%= @conteudo.latitude %>
</p>
<br/>
<p>
  <b>Longitude:</b>
  <%= @conteudo.longitude %>
</p>
<br/>
<p>
  <b>Ativo:</b>
  <%= @conteudo.ativo %>
</p>
<br/>
<p>
  <b>Destaque:</b>
  <%= @conteudo.destaque %>
</p>
<br/>
<p>
  <b>Social:</b>
  <%= @conteudo.social %>
</p>
<br/>
<p>
  <b>URL:</b>
  <%= @conteudo.url %>
</p>

</div>
<div class="caixadireita" style="margin-top:0;">
<p>
	<b>Principal:</b><br/>
	<%= image_tag @conteudo.imagem.url %><br/>
</p>
<p>
  <b>Banner:</b><br/>
  <%= image_tag @conteudo.row_imagem.url %><br/>
</p>
</div>