config/routes.rb
Vitrine::Application.routes.draw do
  
  resources :ingressos_dashboards
  
  resources :acessos
  
  resources :notification
  
  resources :usuarios

  root :to => 'empresas#index'
  
  match 'empresas/conteudo/all' => 'Empresas#get_conteudos'

  resources :empresas do
    resources :conteudos
  end

  resources :empresas do
    resources :tipo_de_ingressos
  end
  
  get "empresas/index"

  resources :sessions


  resources :ingressos
  get "ingressos/index"
  
  match 'ingressos/conteudo/:conteudo_id' => 'Ingressos#get_ingressos_by_conteudo'
  match 'empresas/:empresa_id/conteudos/newvideo/new' => 'Conteudos#newt'
  match 'empresas/:empresa_id/conteudos/newpic/new' => 'Conteudos#newp'

end

app/models/tipo_de_ingresso.rb
class TipoDeIngresso < ActiveRecord::Base
	belongs_to  :empresa
	has_many    :ingressos, dependent: :destroy, :foreign_key => "tipo_de_ingresso_id", :class_name => "Ingresso"
	has_many    :entradas, dependent: :destroy, :foreign_key => "tipo_de_ingresso_id", :class_name => "Entrada"
	has_and_belongs_to_many :conteudos

	accepts_nested_attributes_for :entradas, :allow_destroy => true


	def as_json(options=nil)
     super(:include => :entradas)
  	end

end

app/controllers/tipo_de_ingressos_controller.rb
class TipoDeIngressosController < ApplicationController
  before_filter :get_empresa, :get_conteudos, :checar_permissoes_empresa_dependente

  def get_empresa
    @empresa = Empresa.find(params[:empresa_id])
  end

  def get_conteudos
    @conteudos = @empresa.conteudos
  end

  def index
    @tipo_de_ingressos = @empresa.tipo_de_ingressos

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tipo_de_ingressos.to_json(:include => :entradas) }
    end
  end

  def show
    @tipo_de_ingresso = @empresa.tipo_de_ingressos.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: [@empresa,@tipo_de_ingresso] }
    end
  end

  def new
    @tipo_de_ingresso = TipoDeIngresso.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: [@empresa,@tipo_de_ingresso] }
    end
  end

  def edit
    @tipo_de_ingresso = @empresa.tipo_de_ingressos.find(params[:id])
  end

  def create
    @tipo_de_ingresso = @empresa.tipo_de_ingressos.new(params[:tipo_de_ingresso])

    respond_to do |format|
      if @tipo_de_ingresso.save
        format.html { redirect_to [@empresa,@tipo_de_ingresso], notice: 'Tipo de ingresso was successfully created.' }
        format.json { render json: [@empresa,@tipo_de_ingresso], status: :created, location: [@empresa,@tipo_de_ingresso] }
      else
        format.html { render action: "new" }
        format.json { render json: @tipo_de_ingresso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /empresas/1
  # PUT /empresas/1.json
  def update
    @tipo_de_ingresso = @empresa.tipo_de_ingressos.find(params[:id])

    respond_to do |format|
      if @tipo_de_ingresso.update_attributes(params[:tipo_de_ingresso])
        format.html { redirect_to [@empresa,@tipo_de_ingresso], notice: 'tipo_de_ingresso was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tipo_de_ingresso.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tipo_de_ingresso = @empresa.tipo_de_ingressos.find(params[:id])
    @tipo_de_ingresso.destroy

    respond_to do |format|
      format.html { redirect_to [@empresa,@tipo_de_ingresso] }
      format.json { head :no_content }
    end
  end
end

app/views/tipo_de_ingressos/_entrada_fields.html.erb
<p class="fields">
  <div class="field">
    <%= f.label :data %><br />
    <%= f.datetime_select :data %>
  </div>
  <div class="field">
    <%= f.label :quantidade %><br />
    <%= f.number_field :quantidade %>
  </div>
  <div class="field">
  	<%= f.link_to_remove "Remover entrada" %>
  </div>
</p>

app/views/tipo_de_ingressos/_form.html.erb
<%= nested_form_for([@empresa,@tipo_de_ingresso]) do |f| %>
  <% if @tipo_de_ingresso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_de_ingresso.errors.count, "error") %> Erro ao salvar:</h2>

      <ul>
      <% @tipo_de_ingresso.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :empresa_id %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </div>

  <div class="field">
    <%= f.label :quantidade_ingressos %><br />
    <%= f.number_field :quantidade_ingressos %>
  </div>

  <div class="field">
    <%= f.fields_for :entradas do |builder| %>
      <%= render "entrada_fields", :f => builder %>
    <% end %>
  </div>

  <div class="field">
    <%= f.link_to_add "Adicionar entrada", :entradas %>
  </div>

  <div class="field">
    <%= f.label :conteudos %><br />
    <%= f.select :conteudo_ids, @conteudos.collect {|x| [x.titulo, x.id]}, {}, :multiple => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_de_ingressos/edit.html.erb
<h1>Editar tipo de ingresso</h1>

<%= render 'form' %>

<%= link_to 'Ver', [@empresa, @tipo_de_ingresso] %> |
<%= link_to 'Voltar', empresa_tipo_de_ingressos_path(@empresa) %>

app/views/tipo_de_ingressos/index.html.erb
<div class="page-header">
<div class="page-header">
  <h1  style="text-align: center;margin-bottom: 30px;">Lista de tipos de ingresso</h1>
</div>

<div class="page-content">
  <div class="page-table">
    <table id="content-table">
      <thead>
        <tr>
          <th>Titulo</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @tipo_de_ingressos.each do |tipo_de_ingresso| %>
          <tr>
            <td><%= tipo_de_ingresso.titulo %></td>
            <td><%= link_to image_tag("/assets/shared/show.png", :border=>0, :alt=> 'Mostrar', :title => 'Mostrar Conteudo'), [@empresa, tipo_de_ingresso] %></td>
            <td><%= link_to image_tag("/assets/shared/editar.png", :border=>0, :alt=> 'Editar', :title => 'Editar'), edit_empresa_tipo_de_ingresso_path(@empresa,tipo_de_ingresso) %></td>
            <td><%= link_to image_tag("/assets/shared/remover.png", :border=>0 , :alt => 'Remover', :title => 'Remover'), [@empresa, tipo_de_ingresso], confirm: 'Você tem certeza? ', method: :delete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="page-footer">
    <%= link_to 'Novo tipo de ingresso', new_empresa_tipo_de_ingresso_path(@empresa) %>
    <%= link_to 'Voltar', empresas_path %>
  </div>
</div>

app/views/tipo_de_ingressos/new.html.erb
<div class="page-header">
	<h1>Novo tipo de ingresso</h1>
</div>

<div class="page-form">
	<%= render 'form' %>
</div>


<div class="page-footer">
	<%= link_to 'Voltar', empresa_tipo_de_ingressos_path(@empresa) %>
</div>

app/views/tipo_de_ingressos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @tipo_de_ingresso.titulo %>
</p>

<p>
  <b>Descrição:</b>
  <%= @tipo_de_ingresso.descricao %>
</p>

<p>
  <b>Valor:</b>
  <%= @tipo_de_ingresso.valor %>
</p>

<p>
  <b>Quantidade:</b>
  <%= @tipo_de_ingresso.quantidade_ingressos %>
</p>

<% unless @tipo_de_ingresso.entradas.empty? %>
<p>
	Entradas
</p>
<p>
<% @tipo_de_ingresso.entradas.each do |entrada| %>
  <p>
  	Data
  </p>
  <p>
  	<%= entrada.data %>
  </p>
  <p>
  	Quantidade
  </p>
  <p>
  	<%= entrada.quantidade %>
  </p>
<% end %>
</p>
<% end %>


<%= link_to 'Editar', edit_empresa_tipo_de_ingresso_path(@empresa, @tipo_de_ingresso) %> |
<%= link_to 'Voltar', empresa_tipo_de_ingressos_path(@empresa) %>