config/routes.rb
Vitrine::Application.routes.draw do
  
  resources :ingressos_dashboards
  
  resources :acessos
  
  resources :notification
  
  resources :usuarios

  root :to => 'empresas#index'
  
  match 'empresas/conteudo/all' => 'Empresas#get_conteudos'

  resources :empresas do
    resources :conteudos
  end

  resources :empresas do
    resources :tipo_de_ingressos
  end
  
  get "empresas/index"

  resources :sessions


  resources :ingressos
  get "ingressos/index"
  
  match 'ingressos/conteudo/:conteudo_id' => 'Ingressos#get_ingressos_by_conteudo'
  match 'empresas/:empresa_id/conteudos/newvideo/new' => 'Conteudos#newt'
  match 'empresas/:empresa_id/conteudos/newpic/new' => 'Conteudos#newp'

end

app/models/ingresso.rb
class Ingresso < ActiveRecord::Base
	self.include_root_in_json = true
	belongs_to  :usuario
	belongs_to  :conteudo
	belongs_to  :tipo_de_ingresso

	has_many :acessos
end

app/controllers/ingressos_controller.rb
class IngressosController < ApplicationController

#!/usr/bin/env ruby
require 'openssl'
require 'base64'

  
  # GET /ingressos
  # GET /ingressos.json
  def index
    usuario = Usuario.find_by_id(session[:usuario_id])

    logger.info "Estou acessando ingressos"

    if usuario.tipo == 'administrador'
      @ingressos = Ingresso.all
    else
      if usuario.tipo == 'contratante'
        @ingressos = usuario.empresa.ingressos
      else
        logger.info "CONTRATANTE2"
        @ingressos = usuario.ingressos
      end
    end

    tipo_de_ingresso = :tipo_de_ingresso

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingressos.to_json(:include => [:usuario, :acessos, :tipo_de_ingresso => { :include => :entradas }]) }
    end
  end

  # GET /ingressos/1
  # GET /ingressos/1.json
  def show
    usuario = Usuario.find_by_id(session[:usuario_id])

    if usuario.tipo == 'administrador'
      @conteudo = Conteudo.find(params[:id])
    else
      if usuario.tipo == 'contratante'
        @conteudo = usuario.empresa.conteudos.find(params[:id])
      else
        @conteudo = usuario.conteudos.find(params[:id])
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conteudo.ingressos.to_json(:except => :resposta) }
    end
  end

  # GET /ingressos/new
  # GET /ingressos/new.json
  def new
    @ingresso = Ingresso.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingresso }
    end
  end

  # GET /ingressos/1/edit
  def edit
    @ingresso = Ingresso.find(params[:id])
  end

  # POST /ingressos
  # POST /ingressos.json
  def create
    tipo_de_ingresso = TipoDeIngresso.find(params[:ingresso]['tipo_de_ingresso_id'])
    if tipo_de_ingresso.ingressos == nil or tipo_de_ingresso.ingressos.where("resposta IS NOT NULL").count < tipo_de_ingresso.quantidade_ingressos
      params[:ingresso][:usuario_id] = session[:usuario_id]
      @ingresso = Ingresso.new(params[:ingresso])
    end
    respond_to do |format|
      if @ingresso
        if @ingresso.save
          format.html { redirect_to @ingresso, notice: 'Ingresso was successfully created.' }
          format.json { render json: @ingresso, status: :created, location: @ingresso }
        else
          format.json { render json: @ingresso.errors, status: :unprocessable_entity }
        end
      else
        format.json { render :json => [], status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingressos/1
  # PUT /ingressos/1.json
  def update
    @ingresso = Ingresso.find(params[:id])
    create_response_string(@ingresso)

     message = @ingresso.to_json(:except => [:tipo_de_ingresso_id])

     logger.info message

    if (params[:ingresso][:transacao] != nil && (params[:ingresso][:resposta] == "" || params[:ingresso][:resposta] == nil))
      
      public_key_file = 'public.pem';

      public_key = OpenSSL::PKey::RSA.new(File.read(public_key_file))

      private_key_file = 'private.pem';

      password = "1q2w3e"

      private_key = OpenSSL::PKey::RSA.new(File.read(private_key_file),password)

      # For testing purposes only!
      message = @ingresso.to_json(:except => [:resposta]);

      logger.info message + " <-RESPOSTAAA"

      cipher = OpenSSL::Cipher::Cipher.new('aes-256-cbc')
      cipher.encrypt # Call this before setting key or iv

      cipher.key = random_key = cipher.random_key
      cipher.iv = random_iv = "OTGcipherivkeyOTG"

      logger.info random_key + '<- Tamanho da chave'

      encrypted_key = Base64.encode64(public_key.public_encrypt(random_key))

      # Encrypt plaintext using Triple DES
      
      ciphertext = cipher.update(message)
      ciphertext << cipher.final



      # Base64-encode the ciphertext
      encodedCipherText = Base64.encode64(ciphertext)

      toSend = "#OTG1#" + encrypted_key + "#OT1#" + encodedCipherText

      params[:ingresso][:resposta] = toSend

      logger.info "Texto encriptado ->" + toSend + "  Com a chave ->" + random_key

      xipher = OpenSSL::Cipher::Cipher.new('aes-256-cbc')
      # Base64-decode the ciphertext and decrypt it
      xipher.decrypt
      xipher.key = private_key.private_decrypt(Base64.decode64(encrypted_key))
      xipher.iv = random_iv
      plaintext = xipher.update(Base64.decode64(encodedCipherText))
      plaintext << xipher.final

      logger.info "Texto desencriptado ->" +  plaintext + "  Com a chave ->" + random_key

    end
    respond_to do |format|
      if @ingresso.update_attributes(params[:ingresso])
        format.html { redirect_to @ingresso, notice: 'Ingresso was successfully updated.' }
        format.json { head :no_content }
      else
        format.json { render json: @ingresso.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_response_string(ingresso)
    json = ingresso.to_json
    logger.info json 
    json
  end

  def destroy
    @ingresso = Ingresso.find(params[:id])
    @ingresso.destroy

    respond_to do |format|
      format.html { redirect_to ingressos_url }
      format.json { head :no_content }
    end
  end
  
  def get_ingressos_by_conteudo
    @conteudo = Conteudo.find_by_id(params[:conteudo_id])
    
    @ingressos = @conteudo.ingressos
    
    respond_to do |format|
      format.json { render json: @ingressos.to_json(:include => [:usuario, :tipo_de_ingresso => { :include => :entradas }]) }
    end
  end

end

app/helpers/ingressos_helper.rb
module IngressosHelper
end

app/views/ingressos/_form.html.erb
<%= form_for(@ingresso) do |f| %>
  <% if @ingresso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingresso.errors.count, "error") %> Erro ao salvar:</h2>

      <ul>
      <% @ingresso.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario_id %><br />
    <%= f.text_field :usuario_id %>
  </div>
  <div class="field">
    <%= f.label :tipo_de_ingresso_id %><br />
    <%= f.text_field :tipo_de_ingresso_id %>
  </div>
  <div class="field">
    <%= f.label :conteudo_id %><br />
    <%= f.text_field :conteudo_id %>
  </div>
  <div class="field">
    <%= f.label :transacao %><br />
    <%= f.text_field :transacao %>
  </div>
  <div class="field">
    <%= f.label :resposta %><br />
    <%= f.text_field :resposta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingressos/edit.html.erb
<h1>Editar ingresso</h1>

<%= render 'form' %>

<%= link_to 'Ver', @ingresso %> |
<%= link_to 'Voltar', ingressos_path %>

app/views/ingressos/index.html.erb
<h1>Listing ingressos</h1>

<table>
  <tr>
    <th>Usuario</th>
    <th>Conteudo</th>
    <th>Tipodeingresso</th>
    <th>Transacao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ingressos.each do |ingresso| %>
  <tr>
    <td><%= ingresso.usuario.nome %></td>
    <td><%= ingresso.conteudo.titulo %></td>
    <td><%= ingresso.tipo_de_ingresso.titulo %></td>
    <td><%= ingresso.transacao %></td>
    <td><%= link_to 'Show', ingresso %></td>
    <td><%= link_to 'Edit', edit_ingresso_path(ingresso) %></td>
    <td><%= link_to 'Destroy', ingresso, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ingresso', new_ingresso_path %>

app/views/ingressos/new.html.erb
<div class="page-header">
	<h1>Novo ingresso</h1>
</div>

<div class="page-form">
	<%= render 'form' %>
</div>


<div class="page-footer">
	<%= link_to 'Voltar', ingressos_path %>
</div>

app/views/ingressos/show.html.erb
<%= javascript_include_tag "ingressos" %>


<p id="notice"><%= notice %></p>
<div id="loader"><img src="/assets/spinner.gif"/></div>
<input id="conteudo_id" type="hidden" value="<%=@conteudo.id%>"/>