config/routes.rb
Vitrine::Application.routes.draw do
  
  resources :ingressos_dashboards
  
  resources :acessos
  
  resources :notification
  
  resources :usuarios

  root :to => 'empresas#index'
  
  match 'empresas/conteudo/all' => 'Empresas#get_conteudos'

  resources :empresas do
    resources :conteudos
  end

  resources :empresas do
    resources :tipo_de_ingressos
  end
  
  get "empresas/index"

  resources :sessions


  resources :ingressos
  get "ingressos/index"
  
  match 'ingressos/conteudo/:conteudo_id' => 'Ingressos#get_ingressos_by_conteudo'
  match 'empresas/:empresa_id/conteudos/newvideo/new' => 'Conteudos#newt'
  match 'empresas/:empresa_id/conteudos/newpic/new' => 'Conteudos#newp'

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  
  has_many    :conteudos, dependent: :destroy, :foreign_key => "empresa_id", :class_name => "Conteudo"
  has_many    :usuarios, dependent: :destroy, :foreign_key => "empresa_id", :class_name => "Usuario"
  has_many    :tipo_de_ingressos, dependent: :destroy, :foreign_key => "empresa_id", :class_name => "TipoDeIngresso"
  validates_presence_of :identificador
  validates_uniqueness_of :identificador
  
  
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_filter :checar_permissoes_empresa, :except => :get_conteudos
  before_filter :checar_permissoes, :except => :get_conteudos

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @empresas }
    end
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @empresa }
    end
  end

  # GET /empresas/new
  # GET /empresas/new.json
  def new
    @empresa = Empresa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @empresa }
    end
  end

  # GET /empresas/1/edit
  def edit
    @empresa = Empresa.find(params[:id])
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(params[:empresa])

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render json: @empresa, status: :created, location: @empresa }
      else
        format.html { render action: "new" }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /empresas/1
  # PUT /empresas/1.json
  def update
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      if @empresa.update_attributes(params[:empresa])
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa = Empresa.find(params[:id])
    @empresa.destroy

    respond_to do |format|
      format.html { redirect_to empresas_url }
      format.json { head :no_content }
    end
  end
  
  def get_conteudos
    @conteudos = Conteudo.all
    
    respond_to do |format|
      format.html { render :json => @conteudos }
      format.json { render :json => @conteudos }
    end
  end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_form.html.erb
<%= form_for(@empresa) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> Erro ao salvar:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= link_to image_tag("/assets/shared/voltar.png", :border=>0, :alt=> 'Voltar', :title => 'Voltar'), empresas_path %>
    <%= f.submit "Salvar"%>
  </div>
  <div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>
<div class="caixaesquerda">

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br />
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.telephone_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :identificador %><br />
    <%= f.text_field :identificador %>
  </div>
  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
</div>
<div class="caixadireita">
  <div class="field">
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br />
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :c2dm_email %><br />
    <%= f.text_field :c2dm_email %>
  </div>
  <div class="field">
    <%= f.label :c2dm_registration_id %><br />
    <%= f.text_field :c2dm_registration_id %>
  </div>
  <div class="field">
    <%= f.label :c2dm_password %><br />
    <%= f.password_field :c2dm_password %>
  </div>
</div>
  
<% end %>

app/views/empresas/edit.html.erb
<h1 style="text-align: center;margin-bottom: 30px;">Editar empresa</h1>
<div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>

<%= render 'form' %>

app/views/empresas/index.html.erb
<div class="page-header">
<div class="page-header">
  <h1 style="text-align: center;margin-bottom: 30px;">Lista de empresas</h1>
</div>

<div class="page-content">
  <div class="page-table">
    <table id="content-table">
      <thead>
        <tr>
          <th class="tl_nome" style="width:88%;">Nome</th>
          <th style="width:4%;"></th>
          <th style="width:4%;"></th>
          <th style="width:4%;"></th>
        </tr>
      </thead>
      <tbody>
        <% @empresas.each do |empresa| %>
          <tr>
            <td><%= empresa.nome %></td>
            <td><%= link_to image_tag("/assets/shared/show.png", :border=>0, :alt=> 'Mostrar', :title => 'Mostrar Conteudo'), empresa %></td>
            <td><%= link_to image_tag("/assets/shared/editar.png", :border=>0, :alt=> 'Editar', :title => 'Editar'), edit_empresa_path(empresa) %></td>
            <td><%= link_to image_tag("/assets/shared/remover.png", :border=>0 , :alt => 'Remover', :title => 'Remover'), empresa, confirm: 'Você tem certeza? ', method: :delete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="page-footer">
    <%= link_to 'Nova Empresa', new_empresa_path %>
  </div>
</div>

app/views/empresas/new.html.erb
<h1 style="text-align: center;margin-bottom: 30px;">Nova empresa</h1>
<div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>

<%= render 'form' %>

app/views/empresas/show.html.erb
<h1 style="text-align:center;margin-bottom:30px;">Dados Cadastrais</h1>
<div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>

<p id="notice"><%= notice %></p>
  <%= link_to image_tag("/assets/shared/voltar.png", :border=>0, :alt=> 'Voltar', :title => 'Voltar'), empresas_path %>
  <%= link_to image_tag("/assets/shared/editar2.png", :border=>0, :alt=> 'Editar', :title => 'Editar'), edit_empresa_path(@empresa) %>
  <%= link_to image_tag("/assets/shared/calendar.png", :border=>0, :alt=> 'Eventos', :title => 'Mostrar Eventos'), empresa_conteudos_path(@empresa) %>
  <%= link_to image_tag("/assets/shared/ticket.png", :border=>0, :alt=> 'Tipos de Ingresso', :title => 'Mostrar Tipos de Ingressos'), empresa_tipo_de_ingressos_path(@empresa) %>

<div style="width:100%;height:2px;background:#777;margin-bottom:10px;"></div>

<p>
  <b>Nome:</b>
  <%= @empresa.nome %>
</p>

<p>
  <b>Cnpj:</b>
  <%= @empresa.cnpj %>
</p>

<p>
  <b>Telefone:</b>
  <%= @empresa.telefone %>
</p>

<p>
  <b>Email:</b>
  <%= @empresa.email %>
</p>

<p>
  <b>Identificador:</b>
  <%= @empresa.identificador %>
</p>

<p>
  <b>Apple token:</b>
  <%= @empresa.identificador %>
</p>

<p>
  <b>C2DM email:</b>
  <%= @empresa.c2dm_email %>
</p>

<p>
  <b>C2DM registration id:</b>
  <%= @empresa.c2dm_registration_id %>
</p>